### ISSUE TITLE
cannot support Ultimate NES Remix

### ISSUE THREAD

**Issue by sumire608** [smealum/regionthree#3]
Hello developer, I found the LANUCHER cannot support the game Ultimate NES Remix. (both USA and EU version.)It shows an error occured and please push power bottom.
（test for TMNT and run normally.）
can you check for it?

**Comment by smealum** [comment]
i can't, i don't own that game, sorry.

**Comment by sumire608** [comment]
ORZ...I think it's the most amazing answer I have ever see...
I saw the project from SKY3DS' site and I think you are also a sky3ds' user...

**Comment by smealum** [comment]
I most certainly am not...

**Comment by sumire608** [comment]
well...when you have the time or money consider to buy one...

**Comment by aljomac** [comment]
I think it's more a coders integrity thing rather than a financial issue.

**Comment by yellows8** [comment]
Certain other-region games will throw fatal-error when attempting to load on different-region 3DS systems. Going by the error-code when testing with my own stuff(with a different game), it seems to be an error caused by failing to open localization file(s) stored in RomFS.

AFAICT there isn't any way around this with _just_ the NSS:RebootSystem trick used by regionthree/etc.
